type Comment @mongo(name: "comments") {
	_id: ID!
		title: String
		description: String
		post: Post @link(field: "postId")
}

type Query{
    comments: [Comment]
}

type Mutation {
    createComment(comment:Comment):String
    updateComment(commentId:String, updateDocument: Comment):String
    deleteComment(commentId:String):String
}