type Comment @mongo(name: "comments") {
	_id: ID!
		title: String
		description: String
		post: Post @link(field: "postId")
}

type Query{
    comments(postId:String): [Comment]
}

type PublicComment {
    title: String
    description: String
}

type Mutation {
    createComment(title:String, description: String):String
    updateComment(commentId:String):String
    deleteComment(commentId:String):String
}