type Comment @mongo(name: "comments") {
	_id: ID!
		title: String
		description: String
		post: Post @link(field: "postId")
}

type Post @mongo(name: "posts") {
	_id: ID!
		title: String!
		description: String!
		user: User @link(field: "userId")
		comments: [Comment] @link(to: "post")
}

type User @mongo(name: "users") {
  _id: ID!
  createdAt: Date
  posts: [Post] @link(to: "user")
}

type Query{
    comments: [Comment]
    posts: [Post]
    users: [User]
}

type Mutation {
    addPost(title:String, description: String):String
}