type Post @mongo(name: "posts") {
	_id: ID!
		title: String!
		description: String!
		user: User @link(field: "userId")
		comments: [Comment] @link(to: "post")
}

type Query{
    posts: [Post]
}

type Mutation {
    addPost(title:String, description: String):String
}